name: AQI Full Pipeline (Daily)

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  feature-pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - name: Run feature pipeline
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: python feature_pipeline.py

      - name: Upload features
        uses: actions/upload-artifact@v4
        with:
          name: features-data
          path: features.csv

  training-pipeline:
    needs: feature-pipeline
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - name: Download features
        uses: actions/download-artifact@v4
        with:
          name: features-data

      - name: Run training pipeline
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: python training_pipeline.py
        
      - name: Upload trained model
        uses: actions/upload-artifact@v4
        with:
          name: trained-model-${{ github.run_number }}
          path: saved_models/
